"""Adiciona twitter_id ao User

Revision ID: f435dff664c4
Revises: 
Create Date: 2025-05-04 22:41:48.859939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f435dff664c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['twitter_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('twitter_id')

    # ### end Alembic commands ###
